language: node_js
node_js:
- '5'
install: npm install
script: webpack --config ./webpack-prod.config.js --progress --colors
deploy:
  provider: heroku
  app:
  	master: fjmva
  	staging: fjmva-staging
  api_key:
    secure: jkWhS7uL7lLksNDYzxrRsJ9zuQfSa4wmDfdgxg7pA/I/8V8f7TOAYwF1ff5gzZQV0esGbd69Mzn0kS2AUwD5apLi8Xehyqt2693kgvIX/RKk7gorPGTyT5m86zymuYdimjfGQmiw1hvsx5x7JAZDzjGRpBt+6OkU3x2DYIcWoEDHg7xHO0Jnyg4w0XxZHXbbFIc/fKOXUSByZSyBVi3xvt16v8sxHewtBvsi6yDH+hrnyvdUIMuuIC+WvkDuDyY0f9qk3iSBCZJSShLgtMskn5FIwSItV0+xBvCItJXfJUGIRQLXunzga4Dnv5jek/MoBqANNpIBu0V0ZpVZvlYkmt3PqAqIUb3UQdOTm/YUW23Z9OQYYvPGPEHsKRBBS5Y8PzA6TJNMGHoqP5kB14Q5hivIc2CvY2XkQkF++ScPpx4CiTOw4mPP+hgSw4DgPw6aU+bg2YWiR6Ka9WD/tw+8wP1YpZgGcOFlSfOS09BvPC04FcaT+Y6ORokmRarSwOKdc+3Wja4wp0xu4c7l/tXk0t7sUKqczwE6tEpEXXipv83/3z2KfmRAKMH4x6Vab11wFrefSTRaARpRhH0Klq8zpIWvkmscKcDjEV6FCSzK6p97mcA5egcz/QCaSuWDpL5n+DSEoltcZvEpirOlbJAtcMsfFFGOtU7fe/1Cg6VvP4g=
